#!/usr/bin/env node
"use strict";

/**
 * CSS Build Script
 *
 * Concatenates modular CSS files into a single bundle to eliminate
 * render-blocking @import statements. This improves First Contentful Paint
 * and Largest Contentful Paint metrics.
 *
 * Usage:
 *   node scripts/build-css.js
 *
 * Output:
 *   dist/style.min.css - Concatenated CSS bundle
 */

const fs = require("node:fs");
const path = require("node:path");

const ROOT_DIR = path.resolve(__dirname, "..");
const DIST_DIR = path.join(ROOT_DIR, "dist");
const OUTPUT_FILE = path.join(DIST_DIR, "style.min.css");

// CSS files in load order (matches @import order in style.css)
const CSS_FILES = [
  "style/tokens.css",
  "style/base.css",
  "style/components/dashboard.css",
  "style/components/grid.css",
  "style/components/filters.css",
  "style/components/modal.css",
  "style/components/cards.css",
  "style/utilities.css",
  "style.css",
];

/**
 * Read a CSS file and strip @import statements
 * @param {string} filePath - Path to CSS file
 * @returns {string} CSS content without @imports
 */
function readCssFile(filePath) {
  const fullPath = path.join(ROOT_DIR, filePath);
  if (!fs.existsSync(fullPath)) {
    console.warn(`Warning: CSS file not found: ${filePath}`);
    return "";
  }

  let content = fs.readFileSync(fullPath, "utf8");

  // Remove @import statements (they're handled by concatenation)
  content = content.replace(/@import\s+url\([^)]+\);?\s*/g, "");

  // Add source comment for debugging
  const header = `/* === ${filePath} === */\n`;

  return header + content.trim() + "\n\n";
}

/**
 * Minify CSS by removing comments and extra whitespace
 * @param {string} css - CSS content
 * @returns {string} Minified CSS
 */
function minifyCss(css) {
  return (
    css
      // Remove source comments (keep license comments)
      .replace(/\/\*\s*===.*?===\s*\*\//g, "")
      // Remove multi-line comments (except license)
      .replace(/\/\*(?!\*!)[^*]*\*+(?:[^/*][^*]*\*+)*\//g, "")
      // Remove whitespace around braces and colons
      .replace(/\s*{\s*/g, "{")
      .replace(/\s*}\s*/g, "}")
      .replace(/\s*:\s*/g, ":")
      .replace(/\s*;\s*/g, ";")
      .replace(/\s*,\s*/g, ",")
      // Collapse multiple whitespace
      .replace(/\s+/g, " ")
      // Remove space after last semicolon before brace
      .replace(/;}/g, "}")
      // Trim
      .trim()
  );
}

/**
 * Main build function
 */
function build() {
  console.log("Building CSS bundle...\n");

  // Ensure dist directory exists
  if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
  }

  // Concatenate all CSS files
  let bundle = `/**
 * Dragon's Hoard Atlas - CSS Bundle
 * Auto-generated by scripts/build-css.js
 * Do not edit directly - modify source files in style/ directory
 */\n\n`;

  for (const file of CSS_FILES) {
    const content = readCssFile(file);
    if (content) {
      bundle += content;
      const size = Buffer.byteLength(content, "utf8");
      console.log(`  ✓ ${file} (${(size / 1024).toFixed(1)}KB)`);
    }
  }

  // Write unminified bundle for debugging
  const debugFile = path.join(DIST_DIR, "style.css");
  fs.writeFileSync(debugFile, bundle, "utf8");

  // Minify and write production bundle
  const minified = minifyCss(bundle);
  fs.writeFileSync(OUTPUT_FILE, minified, "utf8");

  const originalSize = Buffer.byteLength(bundle, "utf8");
  const minifiedSize = Buffer.byteLength(minified, "utf8");
  const savings = ((1 - minifiedSize / originalSize) * 100).toFixed(1);

  console.log("\n📦 Bundle created:");
  console.log(`   dist/style.css     ${(originalSize / 1024).toFixed(1)}KB (debug)`);
  console.log(
    `   dist/style.min.css ${(minifiedSize / 1024).toFixed(1)}KB (${savings}% smaller)`
  );

  // Create production index.html with bundled CSS reference
  const indexPath = path.join(ROOT_DIR, "index.html");
  const distIndexPath = path.join(DIST_DIR, "index.html");
  if (fs.existsSync(indexPath)) {
    let indexHtml = fs.readFileSync(indexPath, "utf8");
    // Replace style.css reference with bundled version
    indexHtml = indexHtml.replace(/href="style\.css"/g, 'href="style.min.css"');
    fs.writeFileSync(distIndexPath, indexHtml, "utf8");
    console.log("   dist/index.html    (using bundled CSS)");
  }

  // Create symlinks for assets needed by index.html
  const symlinkDirs = ["app", "data", "covers", "config.js", "favicon.png"];
  for (const item of symlinkDirs) {
    const srcPath = path.join(ROOT_DIR, item);
    const destPath = path.join(DIST_DIR, item);
    if (fs.existsSync(srcPath) && !fs.existsSync(destPath)) {
      try {
        // Use relative path for symlink
        const relativeSrc = path.relative(DIST_DIR, srcPath);
        fs.symlinkSync(relativeSrc, destPath);
        console.log(`   dist/${item} -> ${relativeSrc}`);
      } catch {
        // Symlink may fail on Windows, copy instead
        if (fs.statSync(srcPath).isDirectory()) {
          fs.cpSync(srcPath, destPath, { recursive: true });
        } else {
          fs.copyFileSync(srcPath, destPath);
        }
        console.log(`   dist/${item} (copied)`);
      }
    }
  }

  console.log("\n✅ CSS build complete!");
}

// Run build
build();
