#!/usr/bin/env node

/**
 * Generate config.js from .env values.
 * Ensures Supabase credentials are injected without committing secrets.
 */

import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, "..");

function parseArgs() {
  const args = process.argv.slice(2);
  const options = {};
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === "--env" && args[i + 1]) {
      options.envPath = path.resolve(ROOT_DIR, args[i + 1]);
      i += 1;
    } else if (arg === "--out" && args[i + 1]) {
      options.outputPath = path.resolve(ROOT_DIR, args[i + 1]);
      i += 1;
    }
  }
  return options;
}

function ensureFileExists(filePath, friendlyName) {
  if (!fs.existsSync(filePath)) {
    console.error(`❌ Missing ${friendlyName} at ${path.relative(ROOT_DIR, filePath)}`);
    console.error("Copy .env.example to .env and populate Supabase values.");
    process.exit(1);
  }
}

function buildConfig({ envPath, outputPath }) {
  const resolvedEnv = envPath || path.join(ROOT_DIR, ".env");
  const resolvedOut = outputPath || path.join(ROOT_DIR, "config.js");
  const publicOut = path.join(ROOT_DIR, "public", "config.js");

  ensureFileExists(resolvedEnv, ".env file");
  const result = dotenv.config({ path: resolvedEnv });
  if (result.error) {
    console.error("❌ Failed to parse .env file:", result.error.message);
    process.exit(1);
  }

  const url = (process.env.SUPABASE_URL || "").trim();
  const anonKey = (process.env.SUPABASE_ANON_KEY || "").trim();
  const table = (process.env.SUPABASE_TABLE || "").trim();
  const tables = (process.env.SUPABASE_TABLES || "")
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean);
  const priceToken = (process.env.PRICECHARTING_TOKEN || "").trim();
  const priceCurrency = (process.env.PRICECHARTING_CURRENCY || "").trim();
  const priceCacheHoursRaw = (process.env.PRICECHARTING_CACHE_HOURS || "").trim();
  const priceCacheHours =
    priceCacheHoursRaw && !Number.isNaN(Number(priceCacheHoursRaw))
      ? Number(priceCacheHoursRaw)
      : null;
  const storagePublicBucket = (process.env.SUPABASE_STORAGE_PUBLIC_BUCKET || "").trim();
  const storageAuthBucket = (process.env.SUPABASE_STORAGE_AUTH_BUCKET || "").trim();
  const storageArchiveBucket = (process.env.SUPABASE_STORAGE_ARCHIVE_BUCKET || "").trim();
  const storagePendingBucket = (process.env.SUPABASE_STORAGE_PENDING_BUCKET || "").trim();
  const storageCdnUrl = (process.env.SUPABASE_STORAGE_CDN_URL || "").trim();

  if (!url || !anonKey) {
    console.error("❌ SUPABASE_URL and SUPABASE_ANON_KEY must be defined in .env.");
    process.exit(1);
  }

  const config = { url, anonKey };
  if (tables.length > 0) {
    config.tables = tables;
  }
  if (table) {
    config.table = table;
  }
  if (priceToken || priceCurrency || priceCacheHours) {
    config.pricing = {};
    if (priceToken) config.pricing.token = priceToken;
    if (priceCurrency) config.pricing.currency = priceCurrency.toUpperCase();
    if (priceCacheHours && priceCacheHours > 0) {
      config.pricing.cacheHours = priceCacheHours;
    }
  }
  if (
    storagePublicBucket ||
    storageAuthBucket ||
    storageArchiveBucket ||
    storagePendingBucket ||
    storageCdnUrl
  ) {
    config.storage = {};
    if (storagePublicBucket) config.storage.publicBucket = storagePublicBucket;
    if (storageAuthBucket) config.storage.authBucket = storageAuthBucket;
    if (storageArchiveBucket) config.storage.archiveBucket = storageArchiveBucket;
    if (storagePendingBucket) config.storage.pendingBucket = storagePendingBucket;
    if (storageCdnUrl) config.storage.cdnUrl = storageCdnUrl;
  }

  const content = [
    "// Auto-generated by scripts/generate-config.js",
    "// Update your .env file and rerun the script to change values.",
    `window.__SUPABASE_CONFIG__ = ${JSON.stringify(config, null, 2)};`,
    "",
  ].join("\n");

  fs.writeFileSync(resolvedOut, content, "utf8");
  fs.mkdirSync(path.dirname(publicOut), { recursive: true });
  fs.writeFileSync(publicOut, content, "utf8");

  console.log(`✅ Wrote Supabase config to ${path.relative(ROOT_DIR, resolvedOut)}`);
  console.log(
    `✅ Copied Supabase config to ${path.relative(ROOT_DIR, publicOut)} (bundled)`
  );
}

buildConfig(parseArgs());
